### ISSUE TITLE
Module declares its path as: github.com/loopholelabs/polyglot but was required as: github.com/loopholelabs/polyglot-go

### ISSUE THREAD

**Issue by mthmcalixto** [loopholelabs/frpc-go#42]
Cmd: **`protoc --go-frpc_out=. echo.proto`**

Error file: **`echo.frpc.go`**

![image](https://github.com/loopholelabs/frpc-go/assets/121470728/97df5683-0fdd-49c8-8339-35e13d132a5f)

It is generating the wrong protoc file.

"github.com/loopholelabs/polyglot" works if pasted:

![image](https://github.com/loopholelabs/frpc-go/assets/121470728/9f5b9095-5b77-41d1-a9b8-ae9f1bd7a3d3)

but the error occurs:

![image](https://github.com/loopholelabs/frpc-go/assets/121470728/06a67985-2594-4e33-ba3c-b3586cf0f154)

**Comment by SuperManifolds** [comment]
Hello, this will be solved by #41 which should be completed and merged sometime this week

**Comment by mthmcalixto** [comment]
> Hello, this will be solved by #41 which should be completed and merged sometime this week

Tranks bro :)

**Comment by SuperManifolds** [comment]
Fixed by #41 and included in latest release
