### ISSUE TITLE
How to use windows client?

### ISSUE THREAD

**Issue by Tony-Pi-Network** [loopholelabs/frpc-go#43]
How to use windows client?
Can the Frpc-go windows client directly use Frpc's Frpc.exe and Frcp.toml?

**Comment by SuperManifolds** [comment]
Hi!
fRPC (frisbee RPC) is a Go library for developers to create remote procedure call-based APIs inside their own applications, we do not have any pre-compiled executables.
You might be looking for a different project with a similar name.
